DROP DATABASE IF EXISTS data_warehouse

CREATE DATABASE data_warehouse
CREATE TABLE users( id INT(10) NOT NULL PRIMARY KEY AUTO_INCREMENT, name VARCHAR(64) NOT NULL, lastname VARCHAR(64) NOT NULL, email VARCHAR(64) NOT NULL, admin BOOLEAN NOT NULL, password VARCHAR(64) NOT NULL )
CREATE TABLE regions( id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(64) NOT NULL )
CREATE TABLE countries( id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, region_id INT(10) NOT NULL, name VARCHAR(64) NOT NULL, FOREIGN KEY (region_id) REFERENCES regions(id) )
CREATE TABLE cities( id INT(10) NOT NULL AUTO_INCREMENT PRIMARY KEY, country_id INT(10) NOT NULL, name VARCHAR(64) NOT NULL, FOREIGN KEY (country_id) REFERENCES countries(id) )
